#ifndef ERROR_NO_H
#define ERROR_NO_H

#include "MicroByteConfig.h"

enum ErrorCode
{
    MICROBYTE_OK = 0,
    MICROBYTE_INVALID_PARAMETER = -1001,
    MICROBYTE_NOT_SUPPORTED = -1002,
    MICROBYTE_CALIBRATION_IN_PROGRESS = -1003,
    MICROBYTE_CALIBRATION_REQUIRED = -1004,
    MICROBYTE_NO_RESOURCES = -1005,
    MICROBYTE_BUSY = -1006,
    MICROBYTE_CANCELLED = -1007,
    MICROBYTE_I2C_ERROR = -1010,
    MICROBYTE_SERIAL_IN_USE = -1011,
    MICROBYTE_NO_DATA = -1012
};

enum PanicCode
{
    MICROBYTE_OOM = 20,
    MICROBYTE_HEAP_ERROR = 30,
    MICROBYTE_NULL_DEREFERENCE = 40,
    MICROBYTE_HARDWARE_UNAVAILABLE_ACC = 50,
    MICROBYTE_HARDWARE_UNAVAILABLE_MAG = 51,
};

#endif
