#ifndef MICROBYTE_CONFIG_H
#define MICROBYTE_CONFIG_H

#ifndef MICROBYTE_CONFIG_THREAD_PRIO_LEVELS
#define MICROBYTE_CONFIG_THREAD_PRIO_LEVELS (16)
#endif

#ifndef MICROBYTE_CONFIG_THREAD_MAX
#define MICROBYTE_CONFIG_THREAD_MAX (32)
#endif

#ifndef MICROBYTE_CONFIG_MSG_QUEUE_SIZE
#define MICROBYTE_CONFIG_MSG_QUEUE_SIZE (4)
#endif

#endif
